FROM maven:3.9.9-eclipse-temurin-17 AS build

ARG SERVICE_NAME
WORKDIR /workspace
COPY . .
RUN mvn -pl ${SERVICE_NAME} -am -DskipTests package

FROM eclipse-temurin:17.0.10_7-jre

ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}
WORKDIR /app
COPY --from=build /workspace/${SERVICE_NAME}/target/*.jar /app/app.jar

EXPOSE 10000
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
